Верстка приложения
kursomir/AppComponents pull request #16
Opened 2017-04-19 19:33 UTC by AgDust

Из того что не сделал и осознал это:
1. Ховер при наведении на слайс, и курсор-поинтер, это довольно проблематично и по-моему сбивает с толку, потому что при том что смешиваются интерактивные элементы и обычные. Но если надо можно и доделать
2. Раскраска svg, потому что не знаю как
3. Контент и сайдбар неодинаковой высоты, можно сделать обертку и dispay: table, можно и скриптом потом, я не знаю как лучше...

2017-04-19 20:26 UTC, user1736 commented on src/components/user-menu/index.js
> +export default class UserMenu extends React.Component {
имя компонента не соответствует имени БЭМ блока - потом тяжело это переносить будет

2017-04-19 20:47 UTC, AgDust commented on src/components/user-menu/index.js
> +export default class UserMenu extends React.Component {
Поправил, теперь везде user-menu

2017-04-21 17:02 UTC, user1736 commented
В целом ок, но я не увидел верстки готовых вариантов перевода с кнопками оценки и индикатором статуса

2017-04-21 17:23 UTC, user1736 commented
@basavind, ты будешь смотреть или я мержу?

2017-04-21 18:01 UTC, basavind commented
`slice` надо везде заменить на `chunk` (или давайте подумаем над каким-то другим названием). Это необходимо для того, чтобы логика не расходилась на бэке, в апи и на фронте и мы между собой не путали термины. К тому же возможны коллизии, я думаю ни для кого не секрет, что `slice` — это метод прототипа массива в JS

2017-04-21 18:38 UTC, basavind requested changes
Самые серьезные косяки — несоответствие имен компонентов и их классов.

2017-04-21 18:38 UTC, basavind commented on src/app.story.js
> +// import SliceList from './components/slice-list';
Такое не нужно в репу тянуть — оно уже сохранено в истории, поэтому можно смело удалять.

2017-04-21 18:38 UTC, basavind commented on src/common/fonts/roboto-bold.less
> +}
Желательно в конце всех файлов добавлять пустую строку.

2017-04-21 18:38 UTC, basavind commented on src/components/comments-list/comments-list.less
> +  &__sort-drop-label {
Длинновато получается

2017-04-21 18:38 UTC, basavind commented on src/components/comments-list/comments-list.less
> +  &__add-comment {
Длинновато получается

2017-04-21 18:38 UTC, basavind commented on src/components/control-buttons/control-buttons.less
> +.content__control-buttons {
Не совпадает название файла и стиль компонента. Действительно ли нужен префикс `content_` ?

2017-04-21 18:38 UTC, basavind commented on src/components/control-buttons/index.js
> +            <div className='content__control-buttons'>
Аналогично — действительно нужен префикс `content_`?

2017-04-21 18:38 UTC, basavind commented on src/components/document-titles/document-titles.less
> +.content__titles {
`document-titles` или `content-titles`?

2017-04-21 18:38 UTC, basavind commented on src/components/document-titles/index.js
> +            <div className='content__titles'>
document-titles или content-titles?

2017-04-21 18:38 UTC, basavind commented on src/components/meta-inf/meta-inf.less
> +.meta-inf {
Предлагаю сократить просто до `meta`

2017-04-21 18:38 UTC, basavind commented on src/components/nav-buttons/index.js
> +            <div className='nav-panel'>
`nav-panel` или `nav-buttons`?

2017-04-21 18:38 UTC, basavind commented on src/components/nav-buttons/nav-buttons.less
> +.nav-panel {
`nav-panel` или `nav-buttons`?

2017-04-21 18:38 UTC, basavind commented on src/components/notif-bell/index.js
> +            <a className='header__bell'></a>
`header__bell` или `notif-bell`? И странное сокращение `notif` — лучше не сокращать, а так и писать `notification`.

@user1736  Имеет смысл все иконки объединять в общий неймспейс, вроде `icon__` или `notification-icon__`?

2017-04-21 18:38 UTC, basavind commented on src/components/notif-bell/notif-bell.less
> +.header__bell {
`header__bell` или `notif-bell`?

2017-04-21 18:38 UTC, basavind commented on src/components/sidebar-switch/sidebar-switch.less
> +.sidebar-switch {
может более логично будет назвать `sidebar-contols`? Ну и элементы — `sidebar-control` + `sidebar-control__dictionary`/`sidebar-control__comments`/`sidebar-control__users` и тд?

2017-04-21 19:27 UTC, AgDust commented on src/components/sidebar-switch/sidebar-switch.less
> +.sidebar-switch {
А чем switch плох? Там же переключатель между вкладками

2017-04-21 19:46 UTC, basavind commented on src/components/sidebar-switch/sidebar-switch.less
> +.sidebar-switch {
Тут я не особо настаиваю, мне просто не очень нравится путаница — sidebar switch подразумевает "переключатель сайдбара", и вот смысл немного размывается — а он целиком сайдбар переключает? или включае/выключает сайдбар? Более менее вариант tabs-switch — переключатель табов, но тоже не фонтан.

2017-04-22 10:29 UTC, AgDust commented
Вроде везде пофиксил и получше переименовал

2017-04-22 10:39 UTC, basavind commented on src/components/comments-list/index.js
> +                <div className='comments-list__item'>
Предлагаю для комментов вынести отдельный класс `comment`, потому что нет смысла зацикливаться на комментах, как на элементах списка комментов.
И верстка соответственно упростится и будет более наглядной:
`.comment`
    `.comment__author`
    `.comment__title`
    `.comment__body`
    `.comment__date`
и т.д.

2017-04-22 10:42 UTC, basavind commented on src/components/comments-list/index.js
> +                <div className='comments-list__button comments-list__button-send'></div>
здесь тоже имеет смысл обозвать блок `.comments-controls`, или `.comments-form` а так не совсем понятно, что за кнопочки в списке комментов.

2017-04-22 10:45 UTC, basavind commented on src/components/document-titles/document-titles.less
> +.document-titles__origin {
`.document-title__origin` или `.document__title` + `.document__title--origin`, т.к. это стиль одного заголовка, а не контейнера заголовков

2017-04-22 10:45 UTC, basavind commented on src/components/document-titles/document-titles.less
> +.document-titles__translate {
Аналогично.

2017-04-22 10:49 UTC, basavind commented on src/components/nav-panel/index.js
> +export default class NavPanel extends React.Component {
Может переименовать в `DocumentNavigation` / `DocumentNav` / `DocNav`? `NavPanel` не говорит от чего эта панель навигации и что она дает.

2017-04-22 10:50 UTC, basavind commented on src/components/nav-panel/index.js
> +                <div className='nav-panel__left'></div>
Соответственно если переименовать, то управление будет вида `document-navigation__button` + `document-navigation__button--left`

2017-04-22 11:04 UTC, basavind commented on src/components/meta/index.js
> +export default class Meta extends React.Component {
Давай еще переименуем в `DocumentMeta` — больше информации будет к чему эта мета информация относится и это будет видно сразу при импорте.

2017-04-22 11:13 UTC, basavind commented on src/components/sidebar-controls/index.js
> +                <a className='sidebar-controls__item sidebar-controls__dictionary'></a>
Можно сделать чище и аккуратней — заменить на `sidebar-control` + `sidebar-control--dictionary`

2017-04-22 11:15 UTC, basavind commented on src/components/translations-list/index.js
> +                    <div key={item.id} className='translations-list__item'>
лучше вынести отдельный класс `translation`

2017-04-22 13:03 UTC, user1736 commented on src/components/sidebar-controls/index.js
> +                <a className='sidebar-controls__item sidebar-controls__dictionary'></a>
эм... тут в классах сразу два элемента?

2017-04-22 15:22 UTC, basavind commented on src/components/sidebar-controls/index.js
> +                <a className='sidebar-controls__item sidebar-controls__dictionary'></a>
контейнер и его элементы.

2017-04-22 17:05 UTC, user1736 commented on src/components/sidebar-controls/index.js
> +                <a className='sidebar-controls__item sidebar-controls__dictionary'></a>
я про ``sidebar-controls__item`` и  ``sidebar-controls__dictionary``

на одном html элементе висят классы сразу двух элементов блока - не надо так

2017-04-22 17:07 UTC, basavind commented on src/components/sidebar-controls/index.js
> +                <a className='sidebar-controls__item sidebar-controls__dictionary'></a>
поэтому я и предложил заменить на один класс с модификатором

2017-04-23 11:55 UTC, basavind approved these changes

2017-04-23 11:56 UTC, basavind commented
@user1736 Меня всё более менее устраивает, последнее слово и мерж — за тобой :3

2017-04-23 13:09 UTC, user1736 commented
@basavind давай вливать - замечания на идентичность макету и доработки выкачу после натягивания верстки

2017-04-23 13:47 UTC, merged

2017-04-23 13:48 UTC, basavind commented
@user1736 накинул тебе админских прав