Правки к верстке
kursomir/AppComponents pull request #25
Opened 2017-05-14 15:51 UTC by AgDust

:white_check_mark:  Вынес шрифты в миксины
:white_check_mark:  Стилизовал инпуты (range и button)
:white_check_mark:  Починил размеры и цвета svg
:white_check_mark:  Мелкие правик [отсюда](https://github.com/kursomir/Snowshoe/issues/20)

:x: Пока не поправил отображение юзернейма в хедере
:x: В Chrome radio отображается не совсем правильно, правится легко но я не знаю как это правильно в стилях прописать
:x: Csscomb яндекса подключает миксины в самом низу из-за чего они переопределяют родные стили, Я не понял как это исправить

2017-05-15 12:11 UTC, basavind requested changes
Не все гарнитуры шрифтов подключены, как минимум должен быть еще Roboto Light для `.comment-item__date` `.document-meta__count` `translation-item__info` , также не совпадают гарнитуры у `translation-item__author``chunk-item__number`

Цвет комментариев отличается

2017-05-15 12:11 UTC, basavind commented on src/styles/paginator.less
> +    .regular-text();
Надо перестилизовать пейджер:
![2017-05-15 14 51 32](https://cloud.githubusercontent.com/assets/1267239/26056446/122db380-397e-11e7-929d-4bb3701c3d67.png)

У тебя в настройках текста высота строки в 1.3em перекрывает ранее заданную 60px и всё съезжает к чертям. Как вариант — не играться с высотой строки, а добрать высота пейджера за счет паддинга, а у активного элемента подчеркивание внизу зделать через абсолютное позиционирование в `:after`.

2017-05-15 12:11 UTC, basavind commented on src/styles/content.less
>    box-shadow: -10px 0 20px rgba(0, 0, 0, .2);
`box-shadow: -5px 0 20px rgba(0, 0, 0, .1);`

А то что есть тень, что нет

2017-05-15 12:12 UTC, basavind commented
Да, и у меня тоже не получилось залить свгшки, поэтому можешь заодно у всех свгшек вырезать заливку? :3

2017-05-15 22:09 UTC, AgDust commented
А может не надо издеваться над теми кому это использовать и не ставить текст light, 13px, да еще и светло-серый? Жестоко же... (Я поставил Roboto light и это правда жестоко)

Про цвет комментариев не понял, все цвета вроде совпадают, а в макете никнеймы где-то жирные а где-то нет, но логичнее было бы сделать их жирными

2017-05-16 06:07 UTC, basavind commented
Слева макет, справа — твой вариант
![2017-05-16 9 05 50](https://cloud.githubusercontent.com/assets/1267239/26091954/f6353b28-3a16-11e7-976e-66eec950fe42.png)

2017-05-16 06:08 UTC, basavind commented
По поводу "издеваться" — либо неправильно что-то делаешь, либо вопросы к @gomzz я смотрю на соответствие с макетом

2017-05-16 06:29 UTC, basavind commented
Кстати залез в исходники:

- у `comment-item__author`, `translation-item__author`, `chunk-item__number`, `comment-list__title` гарнитуры Roboto Medium;
- `document-titles__translate` `document-titles__origin` размер шрифта 20px, у тебя 18px
- `comment-item__body` размер шрифта 14px, у тебя 13px
- `comment-list__title` размер шрифта 12px, у тебя 13px
- `translation-item__info` размер шрифта 12px, у тебя 13px
- `comment-form__title` размер шрифта 12px, у тебя 13px

* По цвету комментов — вроде всё совпадает, значит браузер так рендерит, можешь на это забить :3

2017-05-16 06:29 UTC, basavind commented
+ сломалась сборка без гарнитуры `./fonts/roboto/roboto-v16-cyrillic_latin-300.ttf`, надо добавить
![2017-05-16 9 26 55](https://cloud.githubusercontent.com/assets/1267239/26092536/1bcb64b8-3a1a-11e7-9e99-e597a0d33e40.png)

2017-05-16 09:33 UTC, basavind commented
Нашел почему цвета отличаются — там на блок текста непрозрачность добавлена помимо цвета шрифта.

@gomzz причеши пожалуйста исходники, чтобы прозрачность не плавала по слоям, особенно в шрифтах.

2017-05-16 10:29 UTC, AgDust commented
А что за браузер? Я смотрю в chrome и ff, там шрифт и тени рендерятся не так

Насчет издеваться — даже в макете не очень дружелюбно выглядит…

Шрифты поправлю

2017-05-21 12:16 UTC, user1736 commented
Только сейчас обратил внимание - если у тебя форк, то не нужно портить свой мастер, пилить фичи в ветках, мастер надо держать идентичным основному репозиторию

2017-05-21 12:26 UTC, user1736 commented
у имени пользователя в шапке неправильные стили

2017-05-21 12:36 UTC, user1736 requested changes
Колонки все еще сверстаны странно:
- правая колонка не тянется по высоте
- колонки завязаны на размер шапки

Предлагаю сделать флексами

2017-05-21 12:36 UTC, user1736 commented on src/styles/document-navigation.less
> +      &:hover > svg > path {
зачем промежуточное звено ``svg`` тут?

2017-05-21 12:36 UTC, user1736 commented on src/styles/document-navigation.less
> +      & > svg > path {
зачем промежуточное звено ``svg`` тут?

2017-05-21 12:36 UTC, user1736 commented on src/styles/mixins/input-range.less
> +    width: @thumb-width + 3;
``+3``?

2017-05-21 12:36 UTC, user1736 commented on src/styles/mixins/radio-buttons.less
> +  & + label {
тут на лейбл лучше класс повесить - не нужно использовать селектор по тегу, без крайней необходимости

2017-05-21 12:36 UTC, user1736 commented on src/styles/paginator.less
> +      position: absolute;
зачем? О_о

2017-05-21 12:39 UTC, user1736 commented
@AgDust:
- можешь подробнее описать ситуацию с радио кнопками?
- про cssComb я в курсе, согласен что очень неудобно, постараюсь найти рецепт как будет время

2017-05-21 13:34 UTC, basavind commented
По поводу `CSSComb` — если мы его используем, то неплохо включить конфиг в репу

2017-05-21 22:21 UTC, AgDust commented on src/styles/mixins/input-range.less
> +    width: @thumb-width + 3;
Надо `+3px`?

2017-05-21 23:22 UTC, AgDust commented
По поводу радио-кнопок, вот: 
![screenshot from 2017-05-22 04-23-55](https://cloud.githubusercontent.com/assets/20019289/26288202/6845d218-3e95-11e7-89b1-d557cc8a7203.png)
![screenshot from 2017-05-22 04-23-41](https://cloud.githubusercontent.com/assets/20019289/26288201/6844f294-3e95-11e7-8c88-a6a2fc99351c.png)

Сверху отображение в ff, снизу в chrome при одинаковых стилях

2017-05-22 07:09 UTC, basavind commented on src/styles/user-menu.less
> +    .regular-text(14px, #fff);
не обязательно указывать размер (он по-умолчанию и так 14px), можно просто указать имя переменной: `.regular-text(@color: #fff)`

\* это не обязательно менять, просто будь в курсе, что при вызовах миксинов можно указывать значения параметров в произвольном порядке (при условии, что все остальные имеют параметры по-умолчанию) по их имени

2017-05-22 07:11 UTC, basavind commented on src/styles/user-menu.less
> +    .regular-text(14px, #fff);
не обязательно указывать размер (он по-умолчанию и так 14px), можно просто указать имя переменной: .regular-text(@color: #fff)

* это не обязательно менять, просто будь в курсе, что при вызовах миксинов можно указывать значения параметров в произвольном порядке (при условии, что все остальные имеют параметры по-умолчанию) по их имени

2017-05-22 16:14 UTC, agdust commented on src/styles/user-menu.less
> +    .regular-text(14px, #fff);
Понял-уяснил, спасибо :3

2017-05-25 21:18 UTC, basavind approved these changes

2017-05-25 21:23 UTC, merged